"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.environ.get('APP_BASE_DIR')
if not BASE_DIR:
    BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR / "apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!)p^4azkp2uxo(w4=n@6@-!5adumi)q290^2jtcg4md!0^2y+r'

# SECURITY WARNING: don't run with debug turned on in production!
PRODUCTION = True if os.environ.get("APP_PRODUCTION") == "True" else False
DEBUG = True if os.environ.get("APP_DEBUG") == "True" else False
DJANGO_LOGGING = True if os.environ.get("APP_LOGGING") == "True" else False
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("APP_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]
DB_ENGINE = os.environ.get('APP_DB_ENGINE', 'sqlite')
DB_NAME = os.environ.get('APP_DB_NAME', os.path.join(BASE_DIR, '..', 'db', 'db.sqlite3'))
DB_USER = os.environ.get('APP_DB_USER', False)
DB_PASSWD = os.environ.get('APP_DB_PASSWD', False)
DB_PORT = os.environ.get('APP_DB_PORT', False)
DB_HOST = os.environ.get('APP_DB_HOST', False)
MEDIA_ROOT = os.environ.get('APP_MEDIA_ROOT', os.path.join(BASE_DIR, "..", "files"))
MEDIA_URL = os.environ.get('APP_MEDIA_URL', '/files/')
AUTH_USER_MODEL = "users.User"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",

    "apps.users.apps.UsersConfig",
    "apps.blog.apps.BlogConfig",
    "apps.news.apps.NewsConfig",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
if DB_ENGINE == 'sqlite':
    DB_ENGINE = 'django.db.backends.sqlite3'
elif DB_ENGINE == 'postgresql':
    DB_ENGINE = 'django.db.backends.postgresql'

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
    }
}

# Set a db settings from environment variables
if DB_USER:
    DATABASES['default']['USER'] = DB_USER
if DB_NAME:
    DATABASES['default']['NAME'] = DB_NAME
if DB_HOST:
    DATABASES['default']['HOST'] = DB_HOST
if DB_PORT:
    DATABASES['default']['PORT'] = DB_PORT
if DB_PASSWD:
    DATABASES['default']['PASSWORD'] = DB_PASSWD

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

if PRODUCTION:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

else:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "..", 'static')
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

INSTALLED_APPS += [
    "easy_thumbnails",
]

THUMBNAIL_ALIASES = {
    "": {
        "small": {"size": (300, 200), "crop": True},
        "medium": {"size": (800, 600), "crop": True},
        "large": {"size": (1120, 684), "crop": False},
    }
}

THUMBNAIL_BASEDIR = "thumbnails"

# DRF Spectacular
INSTALLED_APPS += [
    "drf_spectacular",
    "drf_spectacular_sidecar",
]

SPECTACULAR_SETTINGS = {
    "TITLE": "Capstone Project API",
    "DESCRIPTION": "API для новостей, блога, пользователей и авторизации.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "TAGS": [
        {"name": "Users", "description": "Регистрация и управление пользователями"},
        {"name": "Auth", "description": "JWT авторизация"},
        {"name": "Blog", "description": "Блог-посты"},
        {"name": "News", "description": "Новости"},
    ],
}

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8199',
    'http://localhost:8199',
    "https://spaceso.maxano.com",
    "https://www.spaceso.maxano.com",
    "http://spaceso.maxano.com",
    "http://www.spaceso.maxano.com",
]